name: 'Deploy'
description: 'Deploy app'
inputs:
  docker-repo:
    description: 'Docker repo used for docker cache'
    default: '322084784142.dkr.ecr.us-east-1.amazonaws.com/docker_cache'
  heroku-api-key:
    description: 'Heroku api key'
    required: true
  heroku-app-name:
    description: 'Heroku app name'
    required: true
  ssh-private-key:
    description: 'SSH private key used to fetch private deps'
    required: true
  cache-version:
    description: 'Docker cache version'
    default: 'v4'

runs:
  using: "composite"
  steps:
     # Set env vars
    - run: echo "HEROKU_API_KEY=${{ inputs.heroku-api-key }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "HEROKU_APP_NAME=${{ inputs.heroku-app-name }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "SSH_AUTH_SOCK=/tmp/ssh_agent.sock" >> $GITHUB_ENV
      shell: bash
    - run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
      shell: bash
    - run: echo "DOCKER_HASH=`sha256sum Dockerfile`" >> $GITHUB_ENV
      shell: bash
    - run: echo "MIX_HASH=`sha256sum mix.lock mix.exs | sha256sum`" >> $GITHUB_ENV
      shell: bash
    - run: echo "CONFIG_HASH=`sha256sum config/prod.exs config/config.exs | sha256sum`" >> $GITHUB_ENV
      shell: bash
    - run: echo "DOCKER_IMAGE=${{ inputs.docker-repo }}:${{ inputs.cache-version }}-${DOCKER_HASH::7}-${MIX_HASH::7}-${CONFIG_HASH::7}" >> $GITHUB_ENV
      shell: bash

    - name: Setup SSH Keys and known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ inputs.ssh-private-key }}"
      shell: bash

    - name: Docker Build (build)
      run: |
        docker build --ssh default .\
          --target build \
          --build-arg MIX_ENV=prod \
          --build-arg APP_NAME=brevity \
          --cache-from $DOCKER_IMAGE-build \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --tag $DOCKER_IMAGE-build
      shell: bash

    - name: Docker push build
      run: docker push $DOCKER_IMAGE-build || true
      shell: bash

    - name: Docker Build (pre-release)
      run: |
        docker build --ssh default .\
          --target pre-release \
          --build-arg MIX_ENV=prod \
          --build-arg APP_NAME=brevity \
          --cache-from $DOCKER_IMAGE-build \
          --cache-from $DOCKER_IMAGE-pre-release \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --tag $DOCKER_IMAGE-pre-release
      shell: bash

    - name: Docker push pre-release
      run: docker push $DOCKER_IMAGE-pre-release || true
      shell: bash

    - name: Build and push docker image
      run: make heroku/build-and-push
      shell: bash

    - name: Run prerelease phase
      run: make heroku/release
      shell: bash
